services:

  java_app:
    container_name: java_app
    image: crud-java:1.0
    build: .
    ports:
      - 8081:8080
    depends_on:
      - java_db
    environment: 
      DATABASE_URL: jdbc:postgresql://java_db:5432/postgres
    volumes:
      - /workspaces/CRUD-con-Docker:/app     
  java_db:
    container_name: java_db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    
